CODE_CONFIGS = {
    "p_application_headers.loan_target_type": {"0": "物件の購入・建築", "7": "お借り換え", "8": "増改築（借り換え有）"},
    "p_application_headers.loan_target": {
        "1": "建売住宅の購入",
        "6": "土地を購入後に建物新築",
        "5": "建物だけ新築(既に土地をお持ちの方)",
        "2": "中古住宅の購入",
        "3": "新築マンションの購入",
        "4": "中古マンションの購入",
    },
    "p_application_headers.land_advance_plan": {"1": "希望する", "0": "希望しない"},
    "p_application_headers.loan_type": {
        "1": "おひとり",
        "2": "ペアローン",
        "3": "収入合算（持分あり）",
        "4": "収入合算（持分なし）",
    },
    "p_borrowing_details__1.bonus_repayment_month": {
        "1": "しない",
        "2": "1・7 月",
        "3": "2・8 月",
        "4": "3 ・9 月",
        "5": "4・10 月",
        "6": "5・11 月",
        "7": "6・12 月",
    },
    "p_borrowing_details__1.repayment_method": {
        "1": "元利均等返済",
        "2": "元金均等返済",
    },
    "p_applicant_persons__0.gender": {"1": "男性", "2": "女性"},
    "p_applicant_persons__0.nationality": {"1": "日本国籍", "2": "外国籍"},
    "p_applicant_persons__0.office_occupation": {
        "1": "会社役員（取締役・監査役）",
        "2": "会社員（管理職）",
        "3": "会社員（一般職）",
        "4": "教職員",
        "5": "自営業",
        "6": "契約社員",
        "7": "派遣社員・嘱託（契約期間１年以上）",
        "8": "派遣社員・嘱託（契約期間１年未満）",
        "9": "公務員・団体職員",
        "10": "農業漁業主",
        "11": "パートアルバイト",
        "12": "年金受給者",
        "99": "その他",
    },
    "p_applicant_persons__0.office_industry": {
        "1": "製造業",
        "2": "農業",
        "3": "林業",
        "4": "漁業",
        "5": "鉱業",
        "6": "建設業",
        "7": "卸売・小売業",
        "8": "金融業",
        "9": "保険業",
        "10": "不動産業",
        "11": "運輸業",
        "12": "電気・ガス・熱供給・水道",
        "13": "飲食・宿泊",
        "14": "医療・福祉",
        "15": "教育・学習支援",
        "16": "その他のサービス業",
        "17": "公務",
        "18": "情報通信業",
        "19": "複合サービス業",
        "99": "その他",
    },
    "p_applicant_persons__0.office_occupation_detail": {
        "1": "医師",
        "2": "歯科医師",
        "3": "弁護士",
        "4": "弁理士",
        "5": "会計士",
        "6": "税理士",
        "7": "司法書士・行政書士",
        "8": "教職・公務員",
        "9": "販売・営業職",
        "10": "事務職",
        "11": "技術職",
        "12": "運転士",
        "99": "その他",
    },
    "p_applicant_persons__0.income_sources": {
        "1": "給与（固定給）",
        "2": "給与（歩合給）",
        "3": "給与（年俸制）",
        "4": "事業収入",
        "5": "不動産収入",
    },
    "p_applicant_persons__0.tax_return": {"1": "はい", "0": "いいえ"},
    "p_applicant_persons__0.tax_return_reasons": {
        "1": "2カ所以上からの給与",
        "2": "事業収入",
        "3": "不動産収入",
        "4": "医療費・寄附金控除",
        "5": "株・配当",
        "6": "給与収入が2000万円超",
        "99": "その他",
    },
    "p_applicant_persons__0.transfer_office": {"1": "はい", "0": "いいえ"},
    "p_applicant_persons__0.maternity_paternity_leave": {"1": "取得予定", "2": "取得中", "3": "取得済み"},
    "p_applicant_persons__0.maternity_paternity_leave_start_date": {"1": "取得予定", "2": "取得中", "3": "取得済み"},
    "p_applicant_persons__1.gender": {"1": "男性", "2": "女性"},
    "p_applicant_persons__1.nationality": {"1": "日本国籍", "2": "外国籍"},
    "p_applicant_persons__1.office_occupation": {
        "1": "会社役員（取締役・監査役）",
        "2": "会社員（管理職）",
        "3": "会社員（一般職）",
        "4": "教職員",
        "5": "自営業",
        "6": "契約社員",
        "7": "派遣社員・嘱託（契約期間１年以上）",
        "8": "派遣社員・嘱託（契約期間１年未満）",
        "9": "公務員・団体職員",
        "10": "農業漁業主",
        "11": "パートアルバイト",
        "12": "年金受給者",
        "99": "その他",
    },
    "p_applicant_persons__1.office_industry": {
        "1": "製造業",
        "2": "農業",
        "3": "林業",
        "4": "漁業",
        "5": "鉱業",
        "6": "建設業",
        "7": "卸売・小売業",
        "8": "金融業",
        "9": "保険業",
        "10": "不動産業",
        "11": "運輸業",
        "12": "電気・ガス・熱供給・水道",
        "13": "飲食・宿泊",
        "14": "医療・福祉",
        "15": "教育・学習支援",
        "16": "その他のサービス業",
        "17": "公務",
        "18": "情報通信業",
        "19": "複合サービス業",
        "99": "その他",
    },
    "p_applicant_persons__1.office_occupation_detail": {
        "1": "医師",
        "2": "歯科医師",
        "3": "弁護士",
        "4": "弁理士",
        "5": "会計士",
        "6": "税理士",
        "7": "司法書士・行政書士",
        "8": "教職・公務員",
        "9": "販売・営業職",
        "10": "事務職",
        "11": "技術職",
        "12": "運転士",
        "99": "その他",
    },
    "p_applicant_persons__1.income_sources": {
        "1": "給与（固定給）",
        "2": "給与（歩合給）",
        "3": "給与（年俸制）",
        "4": "事業収入",
        "5": "不動産収入",
    },
    "p_applicant_persons__1.tax_return": {"1": "はい", "0": "いいえ"},
    "p_applicant_persons__1.tax_return_reasons": {
        "1": "2カ所以上からの給与",
        "2": "事業収入",
        "3": "不動産収入",
        "4": "医療費・寄附金控除",
        "5": "株・配当",
        "6": "給与収入が2000万円超",
        "99": "その他",
    },
    "p_applicant_persons__1.transfer_office": {"1": "はい", "0": "いいえ"},
    "p_applicant_persons__1.maternity_paternity_leave": {"1": "取得予定", "2": "取得中", "3": "取得済み"},
    "p_applicant_persons__1.maternity_paternity_leave_start_date": {"1": "取得予定", "2": "取得中", "3": "取得済み"},
    "p_join_guarantors.gender": {"1": "男性", "2": "女性"},
    "p_application_headers.curr_house_residence_type": {
        "1": "賃貸マンション",
        "2": "公団・アパート",
        "3": "社宅・寮",
        "4": "持ち家（家族名義）",
        "5": "持ち家（本人名義）",
    },
    "p_application_headers.curr_house_schedule_disposal_type": {"1": "売却", "2": "賃貸", "99": "その他"},
    "p_application_headers.curr_house_loan_balance_type": {"1": "有", "0": "無"},
    "p_application_headers.new_house_acquire_reason": {
        "1": "住宅が古い",
        "2": "住宅が狭い",
        "3": "結婚",
        "4": "世帯を分ける（結婚を除く）",
        "5": "環境が悪い",
        "6": "家賃が高い",
        "7": "立ち退き要求",
        "8": "通勤・通学に不便",
        "9": "持ち家希望",
        "99": "その他",
    },
    "p_application_headers.new_house_self_resident": {"1": "はい", "0": "いいえ"},
    "p_application_headers.property_business_type": {"1": "賃貸", "2": "事務所・店舗", "3": "太陽光発電による売電"},
    "p_application_headers.property_land_type": {"1": "賃貸借", "2": "地上権", "3": "使用賃貸"},
    "p_application_headers.property_purchase_type": {"1": "買戻特約付", "2": "保留地", "3": "仮換地"},
    "p_application_headers.property_planning_area": {"1": "市街化調整区域", "2": "都市計画区域外", "99": "その他"},
    "p_application_headers.property_rebuilding_reason": {"1": "既存住宅", "99": "その他"},
    "p_application_headers.property_flat_35_plan": {"1": "ZEH", "2": "Aプラン", "3": "Bプラン"},
    "p_application_headers.property_maintenance_type": {"1": "長期優良住宅", "2": "予備認定マンション"},
    "p_application_headers.property_flat_35_tech": {
        "1": "省エネルギー性",
        "2": "耐震性",
        "3": "バリアフリー性",
        "4": "耐久性・可変性",
    },
    "p_application_headers.property_region_type": {
        "1": "地域連携型（地域活性）",
        "2": "地域連携型（子育て支援）",
        "3": "地方移住支援型",
    },
    "p_application_headers.curr_borrowing_status": {"1": "有", "0": "無"},
    "p_borrowings.borrower": {"1": "申込人本人", "2": "収入合算者（連帯保証人予定者）"},
    "p_borrowings.type": {
        "1": "住宅ローン",
        "2": "カードローン・キャッシング等",
        "3": "アパートローン",
        "4": "事業用のお借入",
        "5": "車のローン",
        "6": "教育ローン",
        "7": "生活費補填のローン",
        "99": "その他",
    },
    "p_borrowings.borrowing_from_house_finance_agency": {"1": "はい", "0": "いいえ"},
    "p_borrowings.loan_purpose": {
        "1": "生活費補填のローン",
        "2": "家電",
        "3": "車",
        "4": "教育",
        "99": "その他",
    },
    "p_borrowings.loan_business_target": {
        "1": "運転資金",
        "2": "設備資金",
        "3": "リース",
        "99": "その他",
    },
    "p_borrowings.category": {
        "1": "ショッピング",
        "2": "キャッシング",
        "3": "カードローン",
    },
    "p_borrowings.scheduled_loan_payoff": {
        "1": "完済予定あり",
        "2": "完済予定なし",
        "3": "住宅ローンプラス利用により完済",
    },
    "p_borrowings.common_housing": {
        "1": "該当する",
        "0": "該当しない",
    },
    "p_borrowings.estate_setting": {
        "1": "有担保",
        "0": "無担保",
    },
    "p_application_headers.refund_source_type": {
        "1": "預貯金",
        "2": "贈与金",
        "3": "住宅売却代金",
        "99": "その他",
    },
    "p_application_headers.rent_to_be_paid_land_borrower": {"1": "申込人本人", "2": "収入合算者（連帯保証人予定者）"},
    "p_application_headers.rent_to_be_paid_house_borrower": {"1": "申込人本人", "2": "収入合算者（連帯保証人予定者）"},
    "p_applicant_persons__0.identity_verification_type": {
        "1": "運転免許証",
        "2": "マイナンバーカード",
        "3": "住民基本台帳カード（顔写真付き）",
    },
    "p_applicant_persons__1.identity_verification_type": {
        "1": "運転免許証",
        "2": "マイナンバーカード",
        "3": "住民基本台帳カード（顔写真付き）",
    },
}
